apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jrye
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0007-tenant/tkrw-pr714-0075-0007-app/devfile-sample-jrye@sha256:686c92ea117ca93715384f6b3bf9556991e4d371d6403ead7126421f6f8b6243
        name: my-nodejs
        resources: {}
status: {}
